/**
 * One contact represents one person in the contact book - SS
 */		

public class Contact {

	private String first_name, last_name, phone_number, email_address, city, state, zip_code, home_address, notes;
	private int uid; //unique id for each contact, default is 0 - SS
	
	/**
	 * creates a new contact instance with UID  - SS
	 * @param first_name
	 * @param last_name
	 */
	public Contact(){
		first_name = "Unassigned";
		last_name = "Unassigned";
		phone_number = "Unassigned";
		email_address = "Unassigned";
		city = "Unassigned";
		state = "Unassigned";
		home_address = "Unassigned";
		zip_code = "Unassigned";
		notes = "Unassigned";
		uid = 13579; //this will be generated by the determineUID() method - SS
	}
	
	/**
	 * set this contact's field values - SS
	 */
	
	public void setFirstName(String str_first_name){
		
	}
	
	public void setLastName(String str_last_name){
		
	}
	
	public void setPhoneNumber(String str_phone_number){
		
	}
	
	public void setEmailAddress(String str_email_address){
		
	}
	
	public void setCity(String str_city){
		
	}
	
	public void setState(String str_state){
		
	}
	
	public void setZIPCode(String str_zip_code){
		
	}
	
	public void setHomeAddress(String str_home_address){
		
	}
	
	public void setNotes(String str_notes){
		
	}
	
	public void setUID(int int_uid){ //calls determineUID() and changes the UID that's input into setUID into the determined UID. - SS
		
	}
	
	public int determineUID(){ //figures out what the UID should be so that it's unique - SS
		return 678;
	}
		
	/**
	 * get the contact's information - SS
	 */
	
	public String getFirstName(){
		return "The first name";
	}
	
	public String getLastName(){
		return "The last name";
	}
	
	public String getPhoneNumber(){
		return "The phone number";
	}
	
	public String getEmailAddress(){
		return "The email address";
	}
	
	public String getCity(){
		return "The city";
	}
	
	public String getState(){
		return "The state";
	}
	
	public String getZIPCode(){
		return "The ZIP code";
	}
	
	public String getHomeAddress(){
		return "The home address";
	}
	
	public int getUID(){
		return 12345;
	}
	
	/**
	 * converts the contact to a string for display in the UI - SS
	 * @param contact
	 * @return
	 */
	public String toString(){
		return "The contact is now a string!";
	}

}
